### PR TITLE
Feature/pop menu

### PR DESCRIPTION
**Pull request by SirriCelles**
### Creating Pop up Modal for projects
- Add popup screen Html and CSS
- pass popup data dynamically via javascript
- add logic to open and close the popup screen

### CODE REVIEW

**Review by nicupop729 — CHANGES_REQUESTED** [review]
Hi @SirriCelles, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request



You have submitted a project, that was done without collaborating when this milestone is a pair-programming activity. Kindly, please invite your peers to collaborate with you on this project following the driver-navigator approach. All group members need to commit to this branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Div685 — CHANGES_REQUESTED** [review]
Hi, **@SirriCelles**, I'm Divyesh your reviewer for this PR :man_technologist: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was done without collaborating, As the previous reviewer mentioned, Please invite your peer to collaborate with you. If your peer is absent or they don't sync with you don't hesitate to get in touch with the **_Student Success team_** they will be able to help you out. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by SirriCelles** [comment]
> Hi, **@SirriCelles**, I'm Divyesh your reviewer for this PR man_technologist
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that was done without collaborating, As the previous reviewer mentioned, Please invite your peer to collaborate with you. If your peer is absent or they don't sync with you don't hesitate to get in touch with the **_Student Success team_** they will be able to help you out.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> _(Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.)_
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **Does not count** into the code reviews limit._

@[Div685](https://github.com/Div685) Since the last rejection I have reached out to my partner on several counts for a collaborative redo but all efforts did not yield any meeting, the last chance was a meeting set for today which still did not hold. I  reached out to student success regarding this issue.

**Comment by SirriCelles** [comment]
Finally got to my partner, and we had a session check, review, and coding time. The changes were made in another branch and merged into this one for a final pull request.

**Review by OmarRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @SirriCelles 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ descriptive PR title and description
- ✔️ descriptive commit messages
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️
- This is My **GitHub**: [@mrramoun](https://github.com/mrramoun)
- This is My **Twitter**: [@ramoun16](https://twitter.com/ramoun16)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
